# Auracast compliant codec configurations settings - 16KHz, 40 octets per frame, low latency
CONFIG_ALIF_BLE_AUDIO_FS_16KHZ=y
CONFIG_ALIF_BLE_AUDIO_OCTETS_PER_CODEC_FRAME_40=y
CONFIG_ALIF_BLE_AUDIO_RTN_2=y
